version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: enterprise-crud-db
    environment:
      POSTGRES_DB: enterprise_crud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: