version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: enterprise-crud-test-db
    environment:
      POSTGRES_DB: enterprise_crud_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"  # Different port from main DB (5433)
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/migrations:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d enterprise_crud_test"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    command: >
      postgres 
        -c log_statement=all 
        -c log_destination=stderr 
        -c log_min_messages=info
        -c max_connections=100
        -c shared_buffers=128MB

volumes:
  postgres_test_data:
    driver: local

networks:
  default:
    name: enterprise-crud-test-network